
redis:
  host: localhost
  port: 7809

jwt:
  access-token:
    secret-key: ${JWT_ACCESS_TOKEN_SECRET_KEY:jwt-access-token-secret-key}
    valid-seconds: 300
  refresh-token:
    secret-key: ${JWT_REFRESH_TOKEN_SECRET_KEY:jwt-refresh-token-secret-key}
    valid-seconds: 604800